# Generated by Django 4.2.4 on 2023-09-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
