# Generated by Django 4.2.5 on 2023-09-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_alter_userprofile_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='microsoftTeam_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
