# Generated by Django 4.2.5 on 2023-10-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_postactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postactivity',
            name='shareable',
        ),
    ]
