# Generated by Django 5.0 on 2025-07-03 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Where_to_Apply',
        ),
    ]
